/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedEditorRouteImport } from './routes/_authenticated/editor'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as SessionTasksChooseOrganizationRouteImport } from './routes/session-tasks.choose-organization'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditorRoute = AuthenticatedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const SessionTasksChooseOrganizationRoute =
  SessionTasksChooseOrganizationRouteImport.update({
    id: '/session-tasks/choose-organization',
    path: '/session-tasks/choose-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/support': typeof SupportRoute
  '/app': typeof AuthenticatedAppRoute
  '/editor': typeof AuthenticatedEditorRoute
  '/docs/$': typeof DocsSplatRoute
  '/session-tasks/choose-organization': typeof SessionTasksChooseOrganizationRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/support': typeof SupportRoute
  '/app': typeof AuthenticatedAppRoute
  '/editor': typeof AuthenticatedEditorRoute
  '/docs/$': typeof DocsSplatRoute
  '/session-tasks/choose-organization': typeof SessionTasksChooseOrganizationRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/support': typeof SupportRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/editor': typeof AuthenticatedEditorRoute
  '/docs/$': typeof DocsSplatRoute
  '/session-tasks/choose-organization': typeof SessionTasksChooseOrganizationRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/playground'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/support'
    | '/app'
    | '/editor'
    | '/docs/$'
    | '/session-tasks/choose-organization'
    | '/templates/$templateId'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/support'
    | '/app'
    | '/editor'
    | '/docs/$'
    | '/session-tasks/choose-organization'
    | '/templates/$templateId'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs'
    | '/playground'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/support'
    | '/_authenticated/app'
    | '/_authenticated/editor'
    | '/docs/$'
    | '/session-tasks/choose-organization'
    | '/templates/$templateId'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  SupportRoute: typeof SupportRoute
  SessionTasksChooseOrganizationRoute: typeof SessionTasksChooseOrganizationRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor': {
      id: '/_authenticated/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthenticatedEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/session-tasks/choose-organization': {
      id: '/session-tasks/choose-organization'
      path: '/session-tasks/choose-organization'
      fullPath: '/session-tasks/choose-organization'
      preLoaderRoute: typeof SessionTasksChooseOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedEditorRoute: typeof AuthenticatedEditorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedEditorRoute: AuthenticatedEditorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  SupportRoute: SupportRoute,
  SessionTasksChooseOrganizationRoute: SessionTasksChooseOrganizationRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
