import { readdir } from "node:fs/promises"
import { basename, join } from "node:path"

const root = join(import.meta.dir, "../assets/catalog")
const output = join(import.meta.dir, "../src/catalog-faces.generated.ts")

const families = [
  { family: "Inter", directory: "inter", prefix: "Inter" },
  {
    family: "Bricolage Grotesque",
    directory: "bricolage-grotesque",
    prefix: "BricolageGrotesque",
  },
  {
    family: "Instrument Sans",
    directory: "instrument-sans",
    prefix: "InstrumentSans",
  },
  {
    family: "Instrument Serif",
    directory: "instrument-serif",
    prefix: "InstrumentSerif",
  },
  { family: "Geist", directory: "geist", prefix: "Geist" },
  { family: "Geist Mono", directory: "geist-mono", prefix: "GeistMono" },
] as const

const weights = new Map([
  ["Thin", 100],
  ["ExtraLight", 200],
  ["Light", 300],
  ["Regular", 400],
  ["Medium", 500],
  ["SemiBold", 600],
  ["Bold", 700],
  ["ExtraBold", 800],
  ["Black", 900],
])

type Face = {
  asset: string
  sha256: string
  weight: number
  style: "normal" | "italic"
}

const generated: Record<string, Face[]> = {}
for (const spec of families) {
  const directory = join(root, spec.directory)
  const files = (await readdir(directory))
    .filter((file) => file.endsWith(".ttf"))
    .sort()
  const faces = await Promise.all(
    files.map(async (file): Promise<Face> => {
      const stem = basename(file, ".ttf")
      const suffix = stem.slice(`${spec.prefix}-`.length)
      const italic = suffix.endsWith("Italic")
      const italicWeightName = suffix.slice(0, -"Italic".length)
      const weightName = italic ? italicWeightName || "Regular" : suffix
      const weight = weights.get(weightName)
      if (!stem.startsWith(`${spec.prefix}-`) || weight === undefined) {
        throw new Error(`Unrecognized catalog face '${spec.directory}/${file}'`)
      }
      const bytes = new Uint8Array(
        await Bun.file(join(directory, file)).arrayBuffer()
      )
      return {
        asset: `catalog/${spec.directory}/${file}`,
        sha256: new Bun.CryptoHasher("sha256").update(bytes).digest("hex"),
        weight,
        style: italic ? "italic" : "normal",
      }
    })
  )
  generated[spec.family] = faces.sort(
    (left, right) =>
      left.weight - right.weight || left.style.localeCompare(right.style)
  )
}

const source =
  `/* Auto-generated by scripts/build-catalog-faces.ts — do not edit. */\n` +
  `import type { OfflineFontCatalogFace } from "./catalog"\n\n` +
  `export const GENERATED_OFFLINE_FONT_FACES = ${JSON.stringify(generated, null, 2)} as const satisfies Readonly<Record<string, readonly OfflineFontCatalogFace[]>>\n`

await Bun.write(output, source)
console.log(
  `Wrote ${output} with ${Object.values(generated).flat().length} faces`
)
