/* Auto-generated by scripts/build-catalog-faces.ts — do not edit. */
import type { OfflineFontCatalogFace } from "./catalog"

export const GENERATED_OFFLINE_FONT_FACES = {
  Inter: [
    {
      asset: "catalog/inter/Inter-ThinItalic.ttf",
      sha256:
        "f25deaa73408f1e55cb165a58c02b974573cb0bee23e4331b1c180917e722245",
      weight: 100,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-Thin.ttf",
      sha256:
        "61cd65815315692082aa22687ee5acae0f467464a25aef58ae786bcb9a6e4c77",
      weight: 100,
      style: "normal",
    },
    {
      asset: "catalog/inter/Inter-ExtraLightItalic.ttf",
      sha256:
        "343d9f380165251ec9569904d0ab8556061ef3ea6b7ac0a738a244151442b4c8",
      weight: 200,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-ExtraLight.ttf",
      sha256:
        "212440e3fc41cbcefef8719858420825986b97e261a635820197d658b052209a",
      weight: 200,
      style: "normal",
    },
    {
      asset: "catalog/inter/Inter-LightItalic.ttf",
      sha256:
        "83c19b3145b10c5997e13ea5e4f5bf261f8eff9f09982d255857406261cacd0a",
      weight: 300,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-Light.ttf",
      sha256:
        "1a45377a85d77be1ee1fb8b8da14abbd6cab6b1867da1da2c4a8f683654622d8",
      weight: 300,
      style: "normal",
    },
    {
      asset: "catalog/inter/Inter-RegularItalic.ttf",
      sha256:
        "f0635603f9576789b7a9603e6f43d0c332ac5d17147cffa696c744bbd3cf9e50",
      weight: 400,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-Regular.ttf",
      sha256:
        "0b59f6b6fc9e8a9ad8032802d1797c4237d9288a3e7b7661517070627b577060",
      weight: 400,
      style: "normal",
    },
    {
      asset: "catalog/inter/Inter-MediumItalic.ttf",
      sha256:
        "aa955ae0835fa27b7f680747b6aab74b233ea96bc7eb89009609df3508c832e2",
      weight: 500,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-Medium.ttf",
      sha256:
        "8999f916eb8d3c9c7094ad352846801099d5736287065ef1e87cb49c204df10d",
      weight: 500,
      style: "normal",
    },
    {
      asset: "catalog/inter/Inter-SemiBoldItalic.ttf",
      sha256:
        "ca8e3c5805209309861d810375d87e8e56c47b5b5b5d18355bde6e3527c5d35c",
      weight: 600,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-SemiBold.ttf",
      sha256:
        "b5996a92e34bb74df9080bf429c33cbed0d3b911926659fcf8b8871ac15ca8a4",
      weight: 600,
      style: "normal",
    },
    {
      asset: "catalog/inter/Inter-BoldItalic.ttf",
      sha256:
        "498a8e0b6eeb3b67eaadc2c3d4cf571c6b669fc803b4f3355c0a134a4d942498",
      weight: 700,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-Bold.ttf",
      sha256:
        "202f240469f916722233188ec316107f6cecaf13b801e9b3939b82b9f7a816d6",
      weight: 700,
      style: "normal",
    },
    {
      asset: "catalog/inter/Inter-ExtraBoldItalic.ttf",
      sha256:
        "a4704b1080491e4511b9194c6b7136866422c99f932d9ae835bedd29fc34a7f0",
      weight: 800,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-ExtraBold.ttf",
      sha256:
        "6885a1141a15827fc0c0ed03b6da7393c77f062abed4a1ed722747899e961656",
      weight: 800,
      style: "normal",
    },
    {
      asset: "catalog/inter/Inter-BlackItalic.ttf",
      sha256:
        "2f36f506c385e933138536aa8de4a45f28da63635fb15af482f2fb0cbc7bc3c4",
      weight: 900,
      style: "italic",
    },
    {
      asset: "catalog/inter/Inter-Black.ttf",
      sha256:
        "99faa906002c840d97e2f19913d79e0d36a3d8cf026c721bf845eeb377ee193c",
      weight: 900,
      style: "normal",
    },
  ],
  "Bricolage Grotesque": [
    {
      asset: "catalog/bricolage-grotesque/BricolageGrotesque-ExtraLight.ttf",
      sha256:
        "46e8e81c5edbfa5bb002d03d81bdb50460952a6f6f1d1dd689fc47cb32fd3cee",
      weight: 200,
      style: "normal",
    },
    {
      asset: "catalog/bricolage-grotesque/BricolageGrotesque-Light.ttf",
      sha256:
        "fb03f75394b3811b9c750710b3bd78bbb11cd728c73a3a06fde470901e9e98e3",
      weight: 300,
      style: "normal",
    },
    {
      asset: "catalog/bricolage-grotesque/BricolageGrotesque-Regular.ttf",
      sha256:
        "6b29f6af01a4a5fbdddb7dd85fdc1323357f22cf770d600e1149b20f31a08b67",
      weight: 400,
      style: "normal",
    },
    {
      asset: "catalog/bricolage-grotesque/BricolageGrotesque-Medium.ttf",
      sha256:
        "f11ff5dd8382b280f442949b5c37ef9e13447c6a66da814fd52a0b68c403ca18",
      weight: 500,
      style: "normal",
    },
    {
      asset: "catalog/bricolage-grotesque/BricolageGrotesque-SemiBold.ttf",
      sha256:
        "ae44236cb810cc79506c30b41bea595bbd309fd6dda2d6b9aadd5aa8b7913483",
      weight: 600,
      style: "normal",
    },
    {
      asset: "catalog/bricolage-grotesque/BricolageGrotesque-Bold.ttf",
      sha256:
        "6aebc23e4a097b41310341a883e42974ac74edbb94e3b46e83d992becf6bc02a",
      weight: 700,
      style: "normal",
    },
    {
      asset: "catalog/bricolage-grotesque/BricolageGrotesque-ExtraBold.ttf",
      sha256:
        "8e56cc4660eaf6fef37d1004aafbed652185993568acf2708e08a388ea8c39a4",
      weight: 800,
      style: "normal",
    },
  ],
  "Instrument Sans": [
    {
      asset: "catalog/instrument-sans/InstrumentSans-RegularItalic.ttf",
      sha256:
        "21d16b9d90c7c6f27de0d3a50c161c15bc7fac192a306bedb67647c1c2a2fa6b",
      weight: 400,
      style: "italic",
    },
    {
      asset: "catalog/instrument-sans/InstrumentSans-Regular.ttf",
      sha256:
        "af784160538649150675a85ebc3359f6205b2dfd9a6e1deea94f5cb78f9eee3f",
      weight: 400,
      style: "normal",
    },
    {
      asset: "catalog/instrument-sans/InstrumentSans-MediumItalic.ttf",
      sha256:
        "1cd8bc9785ba419a3cea7f22e8728a333795b93896511e0e1fa1efc3dad91c87",
      weight: 500,
      style: "italic",
    },
    {
      asset: "catalog/instrument-sans/InstrumentSans-Medium.ttf",
      sha256:
        "aff6ebdd95ce7bf949b4306b7e851d5629dd377703ba6973ea0f3cc7f8c9d1b7",
      weight: 500,
      style: "normal",
    },
    {
      asset: "catalog/instrument-sans/InstrumentSans-SemiBoldItalic.ttf",
      sha256:
        "fe32089ddeb92ca3e54e64bf2e21b0e5b68942feaa8fb41ced6aedf4b688748e",
      weight: 600,
      style: "italic",
    },
    {
      asset: "catalog/instrument-sans/InstrumentSans-SemiBold.ttf",
      sha256:
        "adf9769d954236780e200e12021aed4034014c3941bec8b6f3aa7305ab61effa",
      weight: 600,
      style: "normal",
    },
    {
      asset: "catalog/instrument-sans/InstrumentSans-BoldItalic.ttf",
      sha256:
        "c266bc0f4ca7f6394890c8d6564cef45b6e5eebca07d0be4431d8b495accb142",
      weight: 700,
      style: "italic",
    },
    {
      asset: "catalog/instrument-sans/InstrumentSans-Bold.ttf",
      sha256:
        "32756dc18ade42f9538723384405f193070174e03a7b577101796e18ae40dad2",
      weight: 700,
      style: "normal",
    },
  ],
  "Instrument Serif": [
    {
      asset: "catalog/instrument-serif/InstrumentSerif-Italic.ttf",
      sha256:
        "08939b8bdf534afec24ae0ef5e03f948940cd9a8fe08e7fecbad040e62327385",
      weight: 400,
      style: "italic",
    },
    {
      asset: "catalog/instrument-serif/InstrumentSerif-Regular.ttf",
      sha256:
        "498efd461f6ddfcb7a111bf9a565709d2085d48201d501ead960d93e84ffbb88",
      weight: 400,
      style: "normal",
    },
  ],
  Geist: [
    {
      asset: "catalog/geist/Geist-ThinItalic.ttf",
      sha256:
        "5051abc8c8ee96fa751f512cc6f43e20166329aad38e709161bd61615d95a035",
      weight: 100,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-Thin.ttf",
      sha256:
        "38166b807c16a9c53729901b9dd760f63780a692b1e158405a43f2879b8655f0",
      weight: 100,
      style: "normal",
    },
    {
      asset: "catalog/geist/Geist-ExtraLightItalic.ttf",
      sha256:
        "8dbf0823e74707d8ee215c46927ad3a945479b48ce20ae04b22a2bd82aa4fa9d",
      weight: 200,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-ExtraLight.ttf",
      sha256:
        "31b83371a9c3bf5ea52589d5c8d0db190176a47f6c657ae4b79eb4b0ad39709f",
      weight: 200,
      style: "normal",
    },
    {
      asset: "catalog/geist/Geist-LightItalic.ttf",
      sha256:
        "51115db73e5caa9bc13d962500bcbec04ab7dcd6af8b79e357bfda6b05cdc129",
      weight: 300,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-Light.ttf",
      sha256:
        "14712986b23108dcd02b7c879f45ebfb567823ec966af141af51c2395ef4252f",
      weight: 300,
      style: "normal",
    },
    {
      asset: "catalog/geist/Geist-RegularItalic.ttf",
      sha256:
        "9949f2cae55aadd7dd048063d6db541c97203212964ab906347b6efcaee08f29",
      weight: 400,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-Regular.ttf",
      sha256:
        "58a4bac9a7b901313822aada65bb1469b3c873874e11b3fc88ba75ed9576d98a",
      weight: 400,
      style: "normal",
    },
    {
      asset: "catalog/geist/Geist-MediumItalic.ttf",
      sha256:
        "993aacb7d741c6670c45f8697d034dfe7c8ce2a4119dd835538763c374f22002",
      weight: 500,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-Medium.ttf",
      sha256:
        "35089cbe873bf2764d4ba9810b90f6b93eee45ea37efe4cd83997825b97ab0db",
      weight: 500,
      style: "normal",
    },
    {
      asset: "catalog/geist/Geist-SemiBoldItalic.ttf",
      sha256:
        "516a6b85afb92fbf2e0decd63f95aae4415f412715d348441f90ca67e0c6224a",
      weight: 600,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-SemiBold.ttf",
      sha256:
        "c157d36cc1778633d43f5a0ff92b078bb6de26f5011a6a092b7b6f49fe022fc5",
      weight: 600,
      style: "normal",
    },
    {
      asset: "catalog/geist/Geist-BoldItalic.ttf",
      sha256:
        "8d5a6b87dd7dc5660ec163b9f6cc152e886f2a2328826d1da914297398403734",
      weight: 700,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-Bold.ttf",
      sha256:
        "0b89b2231ea0d3e02d62dd3a20672bc2e64b428b4b3033eb199794ab2404ea31",
      weight: 700,
      style: "normal",
    },
    {
      asset: "catalog/geist/Geist-ExtraBoldItalic.ttf",
      sha256:
        "ac4410d4a67c7d091f09d0865fa965e0dd469e66f6d842b1815fcce97108e3ab",
      weight: 800,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-ExtraBold.ttf",
      sha256:
        "3877bcd88e69dd79ae1890caada926696f05f9789ba0ab46d4a57fc0bd6bfe18",
      weight: 800,
      style: "normal",
    },
    {
      asset: "catalog/geist/Geist-BlackItalic.ttf",
      sha256:
        "297116e635ae1844d1390bbb2cac3094f797828ea9ce6affc5ec0b021b9dbec5",
      weight: 900,
      style: "italic",
    },
    {
      asset: "catalog/geist/Geist-Black.ttf",
      sha256:
        "eb9536ee796617defe6bed5b99ee19a2d7743fc851ebe7ffb59de23a5ced414a",
      weight: 900,
      style: "normal",
    },
  ],
  "Geist Mono": [
    {
      asset: "catalog/geist-mono/GeistMono-ThinItalic.ttf",
      sha256:
        "671050f52e9303df89b404ae85ee01cfb7417c2de612effd55b687fab037f2b8",
      weight: 100,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-Thin.ttf",
      sha256:
        "1dcfffd675d822a7a9392cca8b9ea4e508fc827cf38e0ce8c371893e3868c6f1",
      weight: 100,
      style: "normal",
    },
    {
      asset: "catalog/geist-mono/GeistMono-ExtraLightItalic.ttf",
      sha256:
        "42c4f36e040c50df2d3bac8ed7d92b724f73c6151b325ee340fc970066b74101",
      weight: 200,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-ExtraLight.ttf",
      sha256:
        "2ae8bc43318e0e7e0a042e27e6ab418be303f68aecdf373faf3c1fa8a6bea36c",
      weight: 200,
      style: "normal",
    },
    {
      asset: "catalog/geist-mono/GeistMono-LightItalic.ttf",
      sha256:
        "d5bc1012b72373dc9f7cf4397fa03cbf51ac14d136cee609cc84010f5f281a18",
      weight: 300,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-Light.ttf",
      sha256:
        "83bdc3e823730b6b4501b1ef58eb6e7cf25c9fcc91f634610e81a261a6207786",
      weight: 300,
      style: "normal",
    },
    {
      asset: "catalog/geist-mono/GeistMono-RegularItalic.ttf",
      sha256:
        "74a0a8a318d6712a15a634e42ebb73c2a011b3eb62f7f13a28046ec1ba4d7bbd",
      weight: 400,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-Regular.ttf",
      sha256:
        "341cdaf235d2cdcfa85ff4eed9628381a89422bd3439710c80e45b725db70b2c",
      weight: 400,
      style: "normal",
    },
    {
      asset: "catalog/geist-mono/GeistMono-MediumItalic.ttf",
      sha256:
        "dd955512356b6b16528051db26372466f0ea1df2ae80b9ca63c0e5bc76ecf129",
      weight: 500,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-Medium.ttf",
      sha256:
        "3fc64e39b238a4d4370a35b5226103ab34d04fe741d93bbd59929cab8bbe3500",
      weight: 500,
      style: "normal",
    },
    {
      asset: "catalog/geist-mono/GeistMono-SemiBoldItalic.ttf",
      sha256:
        "cc5dfdc82096ad6adc7cb4b235386afaecff746e11ed124f93869e56190099b7",
      weight: 600,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-SemiBold.ttf",
      sha256:
        "da295c0d1de3ada53531b0722db5e2d6ebb1a40c5653dbc267a8ea75f72be51a",
      weight: 600,
      style: "normal",
    },
    {
      asset: "catalog/geist-mono/GeistMono-BoldItalic.ttf",
      sha256:
        "89fd2047ae29e2db51263f791022df5a1e832ffd573fa5f7a19f71d4d85afafe",
      weight: 700,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-Bold.ttf",
      sha256:
        "c15043f5afc35c3ce2289fc6fa97ba93dfb9c7cf9de3f1554da76a2e749581fe",
      weight: 700,
      style: "normal",
    },
    {
      asset: "catalog/geist-mono/GeistMono-ExtraBoldItalic.ttf",
      sha256:
        "56fb8f88c4ce2fdb029541fddc348a82993a14e63e921c747295cab9eaf11f13",
      weight: 800,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-ExtraBold.ttf",
      sha256:
        "f6f647aa79d1c64226d6eed6bd82ad60584ac41269ad38e749a056aab287efa8",
      weight: 800,
      style: "normal",
    },
    {
      asset: "catalog/geist-mono/GeistMono-BlackItalic.ttf",
      sha256:
        "79d76d91ddca2db45f5094f5dca1e469703bf711a1a0f2555637d2e5504aea43",
      weight: 900,
      style: "italic",
    },
    {
      asset: "catalog/geist-mono/GeistMono-Black.ttf",
      sha256:
        "f2abe3f46da26ab85ee5a150e7902b5fb2fd0a12cf849e29fbc893a894dbaabd",
      weight: 900,
      style: "normal",
    },
  ],
} as const satisfies Readonly<Record<string, readonly OfflineFontCatalogFace[]>>
