import { OFFLINE_FONT_CATALOG } from "@apexmed/fonts"
import { join } from "node:path"

const output = join(import.meta.dir, "../src/fonts/catalog-font-urls.generated.ts")
const assets = OFFLINE_FONT_CATALOG.flatMap(({ faces }) =>
  faces.map(({ asset }) => asset)
)

const imports = assets
  .map(
    (asset, index) =>
      `import font${index}Url from "@apexmed/fonts/assets/${asset}?url"`
  )
  .join("\n")
const entries = assets
  .map((asset, index) => `  ${JSON.stringify(asset)}: font${index}Url,`)
  .join("\n")

await Bun.write(
  output,
  `/* Auto-generated by scripts/build-catalog-font-urls.ts — do not edit. */\n${imports}\n\nexport const catalogFontAssetUrls = Object.freeze({\n${entries}\n})\n`
)
console.log(`Wrote ${output} with ${assets.length} catalog font asset imports`)
