/**
 * Build a hash-pinned font index for static weights.
 * Hashes are SHA-256 of file bytes (not path strings).
 *
 * Usage: bun packages/editor/scripts/build-fonts-index.ts
 */

import { createHash } from "node:crypto"
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

type Face = {
  family: string
  weight: number
  style: "normal" | "italic"
  woff2: string
  ttf: string
  woff2Sha256: string
  ttfSha256: string
}

function sha256File(path: string): string {
  const bytes = readFileSync(path)
  return createHash("sha256").update(bytes).digest("hex")
}

const FACES_SPEC: Array<{
  family: string
  weight: number
  style: "normal" | "italic"
  base: string
}> = [
  { family: "Inter", weight: 400, style: "normal", base: "inter-400" },
  { family: "Inter", weight: 700, style: "normal", base: "inter-700" },
  { family: "Calibri", weight: 400, style: "normal", base: "calibri-400" },
]

async function main(): Promise<void> {
  const assetsDir = join(import.meta.dir, "../assets/fonts")
  const outDir = join(import.meta.dir, "../src/fonts")
  mkdirSync(outDir, { recursive: true })

  if (!existsSync(assetsDir)) {
    throw new Error(`Font assets directory missing: ${assetsDir}`)
  }

  const faces: Face[] = []
  for (const spec of FACES_SPEC) {
    const woff2Path = join(assetsDir, `${spec.base}.woff2`)
    const ttfPath = join(assetsDir, `${spec.base}.ttf`)
    if (!existsSync(woff2Path)) {
      throw new Error(`Missing woff2 asset: ${woff2Path}`)
    }
    if (!existsSync(ttfPath)) {
      throw new Error(`Missing ttf asset: ${ttfPath}`)
    }
    faces.push({
      family: spec.family,
      weight: spec.weight,
      style: spec.style,
      woff2: `/fonts/${spec.base}.woff2`,
      ttf: `/fonts/${spec.base}.ttf`,
      woff2Sha256: sha256File(woff2Path),
      ttfSha256: sha256File(ttfPath),
    })
  }

  const byFamily = new Map<string, Face[]>()
  for (const face of faces) {
    const list = byFamily.get(face.family) ?? []
    list.push(face)
    byFamily.set(face.family, list)
  }

  const index = {
    version: 1,
    generatedAt: new Date().toISOString(),
    families: [...byFamily.entries()].map(([family, familyFaces]) => ({
      family,
      category: "sans-serif",
      faces: familyFaces,
    })),
  }

  const outPath = join(outDir, "fonts-index.generated.json")
  writeFileSync(outPath, `${JSON.stringify(index, null, 2)}\n`)

  // Also emit a TS module the runtime can import without fetch.
  const tsPath = join(outDir, "fonts-index.generated.ts")
  writeFileSync(
    tsPath,
    `/* Auto-generated by scripts/build-fonts-index.ts — do not edit. */\n` +
      `import type { FontIndex } from "./index-core"\n\n` +
      `export const GENERATED_FONT_INDEX = ${JSON.stringify(index, null, 2)} as const satisfies FontIndex\n`
  )

  console.log(`Wrote hash-pinned font index to ${outPath}`)
  console.log(`Families: ${index.families.length}, faces: ${faces.length}`)
  for (const face of faces) {
    console.log(
      `  ${face.family} ${face.weight}: woff2=${face.woff2Sha256.slice(0, 12)}… ttf=${face.ttfSha256.slice(0, 12)}…`
    )
  }
}

await main()
