/* Auto-generated by scripts/build-font-asset-urls.ts — do not edit. */
import font0Url from "@apexmed/fonts/assets/catalog/inter/Inter-ThinItalic.ttf?url"
import font1Url from "@apexmed/fonts/assets/catalog/inter/Inter-Thin.ttf?url"
import font2Url from "@apexmed/fonts/assets/catalog/inter/Inter-ExtraLightItalic.ttf?url"
import font3Url from "@apexmed/fonts/assets/catalog/inter/Inter-ExtraLight.ttf?url"
import font4Url from "@apexmed/fonts/assets/catalog/inter/Inter-LightItalic.ttf?url"
import font5Url from "@apexmed/fonts/assets/catalog/inter/Inter-Light.ttf?url"
import font6Url from "@apexmed/fonts/assets/catalog/inter/Inter-RegularItalic.ttf?url"
import font7Url from "@apexmed/fonts/assets/catalog/inter/Inter-Regular.ttf?url"
import font8Url from "@apexmed/fonts/assets/catalog/inter/Inter-MediumItalic.ttf?url"
import font9Url from "@apexmed/fonts/assets/catalog/inter/Inter-Medium.ttf?url"
import font10Url from "@apexmed/fonts/assets/catalog/inter/Inter-SemiBoldItalic.ttf?url"
import font11Url from "@apexmed/fonts/assets/catalog/inter/Inter-SemiBold.ttf?url"
import font12Url from "@apexmed/fonts/assets/catalog/inter/Inter-BoldItalic.ttf?url"
import font13Url from "@apexmed/fonts/assets/catalog/inter/Inter-Bold.ttf?url"
import font14Url from "@apexmed/fonts/assets/catalog/inter/Inter-ExtraBoldItalic.ttf?url"
import font15Url from "@apexmed/fonts/assets/catalog/inter/Inter-ExtraBold.ttf?url"
import font16Url from "@apexmed/fonts/assets/catalog/inter/Inter-BlackItalic.ttf?url"
import font17Url from "@apexmed/fonts/assets/catalog/inter/Inter-Black.ttf?url"
import font18Url from "@apexmed/fonts/assets/catalog/instrument-sans/InstrumentSans-RegularItalic.ttf?url"
import font19Url from "@apexmed/fonts/assets/catalog/instrument-sans/InstrumentSans-Regular.ttf?url"
import font20Url from "@apexmed/fonts/assets/catalog/instrument-sans/InstrumentSans-MediumItalic.ttf?url"
import font21Url from "@apexmed/fonts/assets/catalog/instrument-sans/InstrumentSans-Medium.ttf?url"
import font22Url from "@apexmed/fonts/assets/catalog/instrument-sans/InstrumentSans-SemiBoldItalic.ttf?url"
import font23Url from "@apexmed/fonts/assets/catalog/instrument-sans/InstrumentSans-SemiBold.ttf?url"
import font24Url from "@apexmed/fonts/assets/catalog/instrument-sans/InstrumentSans-BoldItalic.ttf?url"
import font25Url from "@apexmed/fonts/assets/catalog/instrument-sans/InstrumentSans-Bold.ttf?url"
import font26Url from "@apexmed/fonts/assets/catalog/instrument-serif/InstrumentSerif-Italic.ttf?url"
import font27Url from "@apexmed/fonts/assets/catalog/instrument-serif/InstrumentSerif-Regular.ttf?url"
import font28Url from "@apexmed/fonts/assets/catalog/geist/Geist-ThinItalic.ttf?url"
import font29Url from "@apexmed/fonts/assets/catalog/geist/Geist-Thin.ttf?url"
import font30Url from "@apexmed/fonts/assets/catalog/geist/Geist-ExtraLightItalic.ttf?url"
import font31Url from "@apexmed/fonts/assets/catalog/geist/Geist-ExtraLight.ttf?url"
import font32Url from "@apexmed/fonts/assets/catalog/geist/Geist-LightItalic.ttf?url"
import font33Url from "@apexmed/fonts/assets/catalog/geist/Geist-Light.ttf?url"
import font34Url from "@apexmed/fonts/assets/catalog/geist/Geist-RegularItalic.ttf?url"
import font35Url from "@apexmed/fonts/assets/catalog/geist/Geist-Regular.ttf?url"
import font36Url from "@apexmed/fonts/assets/catalog/geist/Geist-MediumItalic.ttf?url"
import font37Url from "@apexmed/fonts/assets/catalog/geist/Geist-Medium.ttf?url"
import font38Url from "@apexmed/fonts/assets/catalog/geist/Geist-SemiBoldItalic.ttf?url"
import font39Url from "@apexmed/fonts/assets/catalog/geist/Geist-SemiBold.ttf?url"
import font40Url from "@apexmed/fonts/assets/catalog/geist/Geist-BoldItalic.ttf?url"
import font41Url from "@apexmed/fonts/assets/catalog/geist/Geist-Bold.ttf?url"
import font42Url from "@apexmed/fonts/assets/catalog/geist/Geist-ExtraBoldItalic.ttf?url"
import font43Url from "@apexmed/fonts/assets/catalog/geist/Geist-ExtraBold.ttf?url"
import font44Url from "@apexmed/fonts/assets/catalog/geist/Geist-BlackItalic.ttf?url"
import font45Url from "@apexmed/fonts/assets/catalog/geist/Geist-Black.ttf?url"
import font46Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-ThinItalic.ttf?url"
import font47Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-Thin.ttf?url"
import font48Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-ExtraLightItalic.ttf?url"
import font49Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-ExtraLight.ttf?url"
import font50Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-LightItalic.ttf?url"
import font51Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-Light.ttf?url"
import font52Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-RegularItalic.ttf?url"
import font53Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-Regular.ttf?url"
import font54Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-MediumItalic.ttf?url"
import font55Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-Medium.ttf?url"
import font56Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-SemiBoldItalic.ttf?url"
import font57Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-SemiBold.ttf?url"
import font58Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-BoldItalic.ttf?url"
import font59Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-Bold.ttf?url"
import font60Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-ExtraBoldItalic.ttf?url"
import font61Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-ExtraBold.ttf?url"
import font62Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-BlackItalic.ttf?url"
import font63Url from "@apexmed/fonts/assets/catalog/geist-mono/GeistMono-Black.ttf?url"
import font64Url from "@apexmed/fonts/assets/catalog/bricolage-grotesque/BricolageGrotesque-ExtraLight.ttf?url"
import font65Url from "@apexmed/fonts/assets/catalog/bricolage-grotesque/BricolageGrotesque-Light.ttf?url"
import font66Url from "@apexmed/fonts/assets/catalog/bricolage-grotesque/BricolageGrotesque-Regular.ttf?url"
import font67Url from "@apexmed/fonts/assets/catalog/bricolage-grotesque/BricolageGrotesque-Medium.ttf?url"
import font68Url from "@apexmed/fonts/assets/catalog/bricolage-grotesque/BricolageGrotesque-SemiBold.ttf?url"
import font69Url from "@apexmed/fonts/assets/catalog/bricolage-grotesque/BricolageGrotesque-Bold.ttf?url"
import font70Url from "@apexmed/fonts/assets/catalog/bricolage-grotesque/BricolageGrotesque-ExtraBold.ttf?url"

export const fontAssetUrls = Object.freeze({
  "catalog/inter/Inter-ThinItalic.ttf": font0Url,
  "catalog/inter/Inter-Thin.ttf": font1Url,
  "catalog/inter/Inter-ExtraLightItalic.ttf": font2Url,
  "catalog/inter/Inter-ExtraLight.ttf": font3Url,
  "catalog/inter/Inter-LightItalic.ttf": font4Url,
  "catalog/inter/Inter-Light.ttf": font5Url,
  "catalog/inter/Inter-RegularItalic.ttf": font6Url,
  "catalog/inter/Inter-Regular.ttf": font7Url,
  "catalog/inter/Inter-MediumItalic.ttf": font8Url,
  "catalog/inter/Inter-Medium.ttf": font9Url,
  "catalog/inter/Inter-SemiBoldItalic.ttf": font10Url,
  "catalog/inter/Inter-SemiBold.ttf": font11Url,
  "catalog/inter/Inter-BoldItalic.ttf": font12Url,
  "catalog/inter/Inter-Bold.ttf": font13Url,
  "catalog/inter/Inter-ExtraBoldItalic.ttf": font14Url,
  "catalog/inter/Inter-ExtraBold.ttf": font15Url,
  "catalog/inter/Inter-BlackItalic.ttf": font16Url,
  "catalog/inter/Inter-Black.ttf": font17Url,
  "catalog/instrument-sans/InstrumentSans-RegularItalic.ttf": font18Url,
  "catalog/instrument-sans/InstrumentSans-Regular.ttf": font19Url,
  "catalog/instrument-sans/InstrumentSans-MediumItalic.ttf": font20Url,
  "catalog/instrument-sans/InstrumentSans-Medium.ttf": font21Url,
  "catalog/instrument-sans/InstrumentSans-SemiBoldItalic.ttf": font22Url,
  "catalog/instrument-sans/InstrumentSans-SemiBold.ttf": font23Url,
  "catalog/instrument-sans/InstrumentSans-BoldItalic.ttf": font24Url,
  "catalog/instrument-sans/InstrumentSans-Bold.ttf": font25Url,
  "catalog/instrument-serif/InstrumentSerif-Italic.ttf": font26Url,
  "catalog/instrument-serif/InstrumentSerif-Regular.ttf": font27Url,
  "catalog/geist/Geist-ThinItalic.ttf": font28Url,
  "catalog/geist/Geist-Thin.ttf": font29Url,
  "catalog/geist/Geist-ExtraLightItalic.ttf": font30Url,
  "catalog/geist/Geist-ExtraLight.ttf": font31Url,
  "catalog/geist/Geist-LightItalic.ttf": font32Url,
  "catalog/geist/Geist-Light.ttf": font33Url,
  "catalog/geist/Geist-RegularItalic.ttf": font34Url,
  "catalog/geist/Geist-Regular.ttf": font35Url,
  "catalog/geist/Geist-MediumItalic.ttf": font36Url,
  "catalog/geist/Geist-Medium.ttf": font37Url,
  "catalog/geist/Geist-SemiBoldItalic.ttf": font38Url,
  "catalog/geist/Geist-SemiBold.ttf": font39Url,
  "catalog/geist/Geist-BoldItalic.ttf": font40Url,
  "catalog/geist/Geist-Bold.ttf": font41Url,
  "catalog/geist/Geist-ExtraBoldItalic.ttf": font42Url,
  "catalog/geist/Geist-ExtraBold.ttf": font43Url,
  "catalog/geist/Geist-BlackItalic.ttf": font44Url,
  "catalog/geist/Geist-Black.ttf": font45Url,
  "catalog/geist-mono/GeistMono-ThinItalic.ttf": font46Url,
  "catalog/geist-mono/GeistMono-Thin.ttf": font47Url,
  "catalog/geist-mono/GeistMono-ExtraLightItalic.ttf": font48Url,
  "catalog/geist-mono/GeistMono-ExtraLight.ttf": font49Url,
  "catalog/geist-mono/GeistMono-LightItalic.ttf": font50Url,
  "catalog/geist-mono/GeistMono-Light.ttf": font51Url,
  "catalog/geist-mono/GeistMono-RegularItalic.ttf": font52Url,
  "catalog/geist-mono/GeistMono-Regular.ttf": font53Url,
  "catalog/geist-mono/GeistMono-MediumItalic.ttf": font54Url,
  "catalog/geist-mono/GeistMono-Medium.ttf": font55Url,
  "catalog/geist-mono/GeistMono-SemiBoldItalic.ttf": font56Url,
  "catalog/geist-mono/GeistMono-SemiBold.ttf": font57Url,
  "catalog/geist-mono/GeistMono-BoldItalic.ttf": font58Url,
  "catalog/geist-mono/GeistMono-Bold.ttf": font59Url,
  "catalog/geist-mono/GeistMono-ExtraBoldItalic.ttf": font60Url,
  "catalog/geist-mono/GeistMono-ExtraBold.ttf": font61Url,
  "catalog/geist-mono/GeistMono-BlackItalic.ttf": font62Url,
  "catalog/geist-mono/GeistMono-Black.ttf": font63Url,
  "catalog/bricolage-grotesque/BricolageGrotesque-ExtraLight.ttf": font64Url,
  "catalog/bricolage-grotesque/BricolageGrotesque-Light.ttf": font65Url,
  "catalog/bricolage-grotesque/BricolageGrotesque-Regular.ttf": font66Url,
  "catalog/bricolage-grotesque/BricolageGrotesque-Medium.ttf": font67Url,
  "catalog/bricolage-grotesque/BricolageGrotesque-SemiBold.ttf": font68Url,
  "catalog/bricolage-grotesque/BricolageGrotesque-Bold.ttf": font69Url,
  "catalog/bricolage-grotesque/BricolageGrotesque-ExtraBold.ttf": font70Url,
})
